### ISSUE TITLE
希望在 Codemirror 中使用 不知是否有文档帮助

### ISSUE THREAD

**Issue by wph95** [laobubu/MarkdownIME#4]
想在 CodeMirror 中使用，看到已经支持 TinyMCE。
不知是否有计划支持 CodeMirror。

**Comment by laobubu** [comment]
目前没有计划，
而且 CodeMirror 貌似是写代码用的，不是写文章用的诶 =_=

**Comment by wph95** [comment]
https://github.com/NextStepWebs/simplemde-markdown-editor
想在这个编辑器中用 MarkdownIME

**Comment by laobubu** [comment]
MarkdownIME 正如其名，是一种“输入法”（IME），并不完全是富文本编辑器。
1. 如果是要在 [simplemde-markdown-editor](https://github.com/NextStepWebs/simplemde-markdown-editor) 实现 MarkdownIME 的体验话，需要用别的方式，而且会略烦。
2. 如果是要达到其样式的话，可以自己编写（或者借鉴一点儿）CSS 样式。
3. 如果是要一个工具栏的话，还是可以自己写一个的说，使用 `div.execCommand('insertText',false, '**')` 之类的，虽然感觉意思不是很大。
4. 如果是其他情况，再跟帖吧。。。
