### ISSUE TITLE
提示“MarkdownIME.min.js:formatted:1080 Uncaught TypeError: Cannot read property 'defaultView' of undefined”

### ISSUE THREAD

**Issue by EruditePig** [laobubu/MarkdownIME#5]
Chrome版本53.0.2785.116 (64-bit)，在小众软件和Github里都测试了，不行~

**Comment by kevinlvhsl** [comment]
我也遇到这个问题， 请问有时间解决吗？  chrome版本56.

**Comment by laobubu** [comment]
@EruditePig 那两个网站都是纯文本输入框，用不了的。如果有兴趣，可以试着使用 [HyperMD](https://github.com/laobubu/HyperMD/) 间接实现你所想要的功能

@kevinlvhsl 是否可以提供一个测试地址？
