### ISSUE TITLE
markdown语法初始化怎么掉用？

### ISSUE THREAD

**Issue by goodbuildwhc** [laobubu/MarkdownIME#8]
页面加载内容，页面之间显示对应的html格式怎么实现
如：### 欢迎
显示为 <h3>欢迎</h3>

**Comment by laobubu** [comment]
在 `contentEditable` 的元素中直接写对应的HTML就可以了。

```html
<div id="editor" contentEditable="true">
<h3>欢迎</h3>
<p>你可以直接编辑这个富文本输入区域</p>
</div>
```

然后初始化 MarkdownIME 即可

**Comment by laobubu** [comment]
如果是进入之前的操作，可以采用 [marked](https://github.com/chjj/marked) 之类的库先把 Markdown 转换为 HTML，更新输入框的内容，然后再初始化 MarkdownIME。

MarkdownIME 的转换方式只适用于将较短的 Markdown 文字片段~~打补丁~~转换为 HTML
